# Generated by Django 5.2.8 on 2025-11-12 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='ทะเบียนรถ')),
                ('model', models.CharField(max_length=100, verbose_name='รุ่นรถ')),
                ('last_service_mileage', models.IntegerField(default=0, verbose_name='เลขไมล์ที่เข้าศูนย์ล่าสุด')),
                ('service_interval_km', models.IntegerField(default=10000, verbose_name='ระยะที่ต้องเข้าศูนย์ (กม.)')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='รายละเอียดปัญหา')),
                ('status', models.CharField(choices=[('NEW', 'แจ้งใหม่'), ('IN_PROGRESS', 'กำลังดำเนินการ'), ('RESOLVED', 'แก้ไขแล้ว')], default='NEW', max_length=20, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ผู้แจ้ง')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection.vehicle', verbose_name='รถที่พบปัญหา')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odometer_reading', models.IntegerField(verbose_name='เลขไม่ปัจจุบัน')),
                ('fuel_level', models.CharField(max_length=20, verbose_name='ระดับน้ำมัน')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='หมายเหตุอื่นๆ')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='เวลาที่บันทึก')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='พนักงานขับรถ')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection.vehicle', verbose_name='รถที่ตรวจ')),
            ],
        ),
    ]
