# Generated by Django 5.2.8 on 2025-11-14 04:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='ทะเบียนรถ')),
                ('model', models.CharField(max_length=100, verbose_name='รุ่น/ยี่ห้อ')),
                ('vehicle_type', models.CharField(blank=True, max_length=50, verbose_name='ประเภทรถ')),
                ('last_service_mileage', models.PositiveIntegerField(default=0, verbose_name='เลขไมล์เข้าศูนย์ครั้งล่าสุด')),
                ('service_interval_km', models.PositiveIntegerField(default=10000, verbose_name='ระยะเข้าศูนย์ (กม.)')),
            ],
            options={
                'verbose_name': 'รถยนต์',
                'verbose_name_plural': 'ข้อมูลรถยนต์',
            },
        ),
        migrations.CreateModel(
            name='ProblemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่แจ้ง')),
                ('description', models.TextField(verbose_name='รายละเอียดปัญหา')),
                ('status', models.CharField(choices=[('NEW', 'ใหม่'), ('IN_PROGRESS', 'กำลังซ่อม'), ('RESOLVED', 'ซ่อมแล้ว')], default='NEW', max_length=20, verbose_name='สถานะ')),
                ('is_read', models.BooleanField(default=False, verbose_name='แอดมินอ่านแล้ว')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้รายงาน')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection.vehicle', verbose_name='รถ')),
            ],
            options={
                'verbose_name': 'รายงานปัญหา',
                'verbose_name_plural': 'รายการแจ้งซ่อม',
            },
        ),
        migrations.CreateModel(
            name='InspectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันที่ตรวจ')),
                ('odometer_reading', models.PositiveIntegerField(verbose_name='เลขไมล์ (กม.)')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('checklist_data', models.JSONField(default=dict, verbose_name='ข้อมูล Checklist')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='คนขับ')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection.vehicle', verbose_name='รถ')),
            ],
            options={
                'verbose_name': 'บันทึกการตรวจ',
                'verbose_name_plural': 'ประวัติการตรวจทั้งหมด',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='วันที่')),
                ('status', models.CharField(choices=[('PENDING', 'รอตรวจ'), ('DONE', 'ตรวจแล้ว')], default='PENDING', max_length=10, verbose_name='สถานะ')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='คนขับ')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection.vehicle', verbose_name='รถ')),
            ],
            options={
                'verbose_name': 'ตารางเวร',
                'verbose_name_plural': 'ตารางเวร',
                'unique_together': {('driver', 'vehicle', 'date')},
            },
        ),
    ]
