# Generated by Django 5.2.8 on 2025-11-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionrecord',
            name='checklist_data',
            field=models.JSONField(blank=True, null=True, verbose_name='ข้อมูลเช็คลิสต์'),
        ),
    ]
