# Generated by Django 5.2.8 on 2025-11-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0002_inspectionrecord_checklist_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionrecord',
            name='fuel_level',
            field=models.CharField(choices=[('F', 'เต็มถัง (F)'), ('3/4', '3/4'), ('1/2', 'ครึ่งถัง (1/2)'), ('1/4', '1/4'), ('E', 'ใกล้หมด (E)')], default='F', max_length=5, verbose_name='ระดับน้ำมัน'),
        ),
    ]
