# Generated by Django 5.2.8 on 2025-11-12 12:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0003_alter_inspectionrecord_fuel_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='วันที่ตรวจ')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='พนักงานขับรถ')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection.vehicle', verbose_name='รถที่ต้องตรวจ')),
            ],
            options={
                'verbose_name': 'ตารางเวร',
                'verbose_name_plural': 'ตารางเวร',
                'unique_together': {('vehicle', 'date')},
            },
        ),
    ]
