# Generated by Django 5.2.8 on 2025-11-12 12:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0004_schedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('driver', 'vehicle', 'date')},
        ),
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('PENDING', 'ยังไม่ตรวจ'), ('DONE', 'ตรวจแล้ว')], default='PENDING', max_length=10),
        ),
    ]
